# file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf
TTS_SESSION_COMMANDS=(opencode .)
S_LOG=file | echo # echo will echo to stdout, file will write to TS_LOG_FILE
TS_LOG_FILE=<file> # will write logs to <file> Defaults to ~/.local/share/tmux-sessionizer/tmux-sessionizer.logs

