# vim:filetype=conf
# file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf

# Override default search paths
TS_SEARCH_PATHS=(
  "$HOME/Dropbox/projects/"
  "$HOME/Dropbox/Vault/"
  "$HOME/.config"
)

# Add additional search paths (optional)
TS_EXTRA_SEARCH_PATHS=(
  "$HOME/"
)

# # if set this override the TS_MAX_DEPTH (1)
TS_MAX_DEPTH=2

# Long-running session commands
TS_SESSION_COMMANDS=(
  "python manage.py runserver"
  "http-server"
  "browser-sync start --server --files '**/*.html' '**/*.css' '**/*.js'"
  "npm run dev"
)

# Logging configuration
TS_LOG="file"   # echo prints to stdout
TS_LOG_FILE="$HOME/.local/share/tmux-sessionizer/tmux-sessionizer.logs"
