# vim:filetype=conf
# file: ~/.config/tmux-sessionizer/tmux-sessionizer.conf

# Override default search paths
TS_SEARCH_PATHS=(
  "$HOME/projects/"
  "$HOME/Studie/"
  "$HOME/"
)

# Add additional search paths (optional)
TS_EXTRA_SEARCH_PATHS=(
  "$HOME/.config"
)

# # if set this override the TS_MAX_DEPTH (1)
TS_MAX_DEPTH=2

# Long-running session commands
TS_SESSION_COMMANDS=(
  "http-server"
  "nvim ."
  "python manage.py runserver"
  "npm run dev"
)

# Logging configuration
TS_LOG="~/.local/share/tmux-sessionizer/tmux-sessionizer.logs"   # echo prints to stdout
TS_LOG_FILE="$HOME/.local/share/tmux-sessionizer/tmux-sessionizer.logs"
