bindd = SUPER SHIFT, V, VSCode, exec, code

# Unbind SUPER J & K & L from toggle splitscreen, show key bindings, and map SUPER down to toggle splitscreen
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
bindd = SUPER CTRL SHIFT, L, Toggle workspace layout, exec, omarchy-hyprland-workspace-layout-toggle
bindd = SUPER CTRL, J, Toggle window split, layoutmsg, togglesplit
bindd = SUPER, B, Show key bindings, exec, omarchy-menu-keybindings

# bind hyperbars toggle on/off
bind = SUPER ALT, B, exec, bash -c 'hyprctl keyword plugin:hyprbars:enabled $(hyprctl getoption plugin:hyprbars:enabled -j | jq -r ".int | if . == 1 then 0 else 1 end")'

# Bind move focus keys and move window keys to use vim motions
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, J, Move focus down, movefocus, d

bindd = SUPER ALT, H, Move window to group on left, moveintogroup, l
bindd = SUPER ALT, L, Move window to group on right, moveintogroup, r
bindd = SUPER ALT, K, Move window to group on top, moveintogroup, u
bindd = SUPER ALT, J, Move window to group on bottom, moveintogroup, d

bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, K, movewindow, u
bind = SUPER SHIFT, J, movewindow, d

# Brightness controll
bindd = SUPER, F11, Toggle brightness off, exec, /home/emiel/.local/scripts/brightness-off
bindd = SUPER, F12, Toggle brightness max, exec, /home/emiel/.local/scripts/brightness-max
